on:
  push:
    paths:
      - 'steamtinkerlaunch'
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'steamtinkerlaunch'

name: "ShellCheck"
permissions: {}

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    # Source: https://stackoverflow.com/a/65946732/1952066
    # a push event from the origin repo, or a PR from external repo
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'sonic2kk/steamtinkerlaunch' }}
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          version: v0.10.0
